### ISSUE TITLE
How to enable logging?

### ISSUE THREAD

**Issue by Kipriz** [grails-plugins/grails-database-migration#103]
For Grails 2.4 migration plugin has a lot of logging that was very useful.
Does version 3.0.0 of migration plugin support any kind of logging?
If no, how to better implement logging from your point of view?

**Comment by jameskleeh** [comment]
logback.groovy:
`logger("org.liquibase", INFO, ['STDOUT'], false)`

**Comment by mike-strauch** [comment]
Has this changed at all in more recent releases?  The only logging I ever seem to get is:

```
INFO 8/25/17 12:46 PM: liquibase: Can not use class org.grails.plugins.databasemigration.liquibase.GormDatabase as a Liquibase service because it does not have a no-argument constructor
Grails application running at http://localhost:8080 in environment: development
```

Here's what I've got in my logback config:

```
logger 'org.liquibase', DEBUG, ['STDOUT'], false
```

I've tried different values for the level: DEBUG, TRACE, INFO

**Comment by fsobanski** [comment]
I've got the same problem as mike-strauch since I have upgraded to Grails 3.3.4. With Grails 3.2.0, I got log output about the `change log lock` and about all the migrations that got executed. After the upgrade there is only that one line from liquibase.

@mike-strauch Have you been able to solve that problem in your case?
