### ISSUE TITLE
Hibernate 5 support

### ISSUE THREAD

**Issue by bassmartin** [grails-plugins/grails-database-migration#64]
The plugin is not compatible with Hibernate 5. There is an error thrown :
`:dbmGenerateGormChangelogCommand execution error: org.hibernate.cfg.Configuration.getTableMappings()Ljava/util/Iterator;`

**Comment by jesperronn** [comment]
Could be nice with Hibernate 5 support. @bassmartin can you fix, or do you have any idea who can fix it?

**Comment by salex772** [comment]
If this plugin do not support Hibernate 5 it's sadly.

**Comment by Schlogen** [comment]
There is no `liquibase-hibernate5` module available yet https://github.com/liquibase/liquibase-hibernate/issues/96

**Comment by zyro23** [comment]
did you see the linked linked repo there (https://github.com/jean-merelis/liquibase-hibernate5)? seems like @jean-merelis is working on `liquibase-hibernate5` it but it says
> For now only supports ejb3 database

which i am afraid might not be enough for the grails/gorm/dbm integration.. so maybe some collaboration over there could steer it in the right direction?

**Comment by Schlogen** [comment]
@zyro23 I did see that. Perhaps it will be necessary for us to implement that. It doesn't seem like it would be incredibly difficult.

**Comment by animator013** [comment]
Seems like support for hibernate 5 is getting somewhere on liquibase side. On master branch of https://github.com/liquibase/liquibase-hibernate is support for hibernate 5 (5.0.10).

**Comment by animator013** [comment]
Hibernate 5 support from liquibase has been pushed to maven.

**Comment by jameskleeh** [comment]
@animator013 @zyro23 @alex-shamshurin @bassmartin @jesperronn If all of you can try out version `3.0.0.BUILD-SNAPSHOT` of the plugin, I have integrated liquibase-hibernate5.

**Comment by erichelgeson** [comment]
Tested the snapshot release and it looks good! Just observations - 
* I had an old version of liqudbase in my build.gradle due to this https://github.com/grails-plugins/grails-database-migration/commit/b2915891627589b0e664269bb844f13bc86ea22c
* `INFO 10/27/16 9:26 PM: liquibase: Can not use class org.grails.plugins.databasemigration.liquibase.GormDatabase as a Liquibase service because it does not have a no-argument constructor` is a harmless message but shows every app startup
* Migration logs are not displayed anymore (probably just need to adjust my logback)
* It worked fine with https://github.com/kaleidos/grails-postgresql-extensions/pull/99 
* Every changeset now has `objectQuotingStrategy: "QUOTE_ALL_OBJECTS"`  - have to read up on what that means tomorrow

**Comment by jameskleeh** [comment]
Closing this due to my testing it is generally working. Create new issues for any problems found
